version: '3'
services:
    # redis:
    #     image: "redis"
    #     ports:
    #         - 6379:6379
    #     volumes:
    #         - ./data/redis:/data
    #         - ./logs/redis:/logs
    #         - ./config/redis.conf:/usr/local/etc/redis/redis.conf"
    #     command:
    #         redis-server /usr/local/etc/redis/redis.conf

    # mysql:
    #     image: "mysql"
    #     ports:
    #         - "3306:3306"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "mysql2020"
    #         MYSQL_USER: "chao"
    #         MYSQL_PASSWORD: "mysql2020"
    #     volumes:
    #         - ./data/mysql:/var/lib/mysql:rw
    #         - ./config/my.cnf:/etc/my.cnf:rw
    #         - ./init/mysql:/docker-entrypoint-initdb.d/

    mongo:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
          TZ: Asia/Shanghai
          MONGO_INITDB_DATABASE: stock
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: mongo2020
        volumes:
            - ./data/mongo:/data/db
            - ./init/mongo:/docker-entrypoint-initdb.d/
        command: mongod
    
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        links:
            - mongo:mongo
        depends_on:
            - mongo
        ports:
            - "27018:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongo2020
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: mongo2020
    
# docker-compose up -d